### ISSUE TITLE
Create issue using label and milestones

### ISSUE THREAD

**Issue by naokidney** [Kristinejosami/hello-world#8]
Create issue using label and milestones, assign the issue to you, and set a project

**Comment by naokidney** [comment]
@kristinejosami I can't see any issues that you made

**Comment by naokidney** [comment]
@kristinejosami please share the link of the issue that you created

**Comment by kristinejosami** [comment]
https://github.com/kristinejosami/hello-world/issues/11

**Comment by naokidney** [comment]
@kristinejosami LGTM 👍

**Comment by kristinejosami** [comment]
What's LGTM?
